"""Initial migration

Revision ID: 616bed3322b8
Revises: 
Create Date: 2024-03-16 12:14:02.417533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616bed3322b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email_address', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('bin_level', sa.Integer(), nullable=False),
    sa.Column('is_full', sa.Boolean(), nullable=False),
    sa.Column('is_half', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
