"""Initial migration

Revision ID: feba46da1ec8
Revises: 616bed3322b8
Create Date: 2024-05-26 13:23:46.534733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feba46da1ec8'
down_revision = '616bed3322b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bin_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bin_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bin_level')
        batch_op.drop_column('is_full')
        batch_op.drop_column('is_half')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_half', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('is_full', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('bin_level', sa.INTEGER(), nullable=False))

    op.drop_table('bin_status')
    op.drop_table('bin_location')
    # ### end Alembic commands ###
